### ISSUE TITLE
Complete task 4.3.1 “Joint cohort variant genotyping” (meta-issue)

### ISSUE THREAD

**Issue by tskir** [CINECA-project/wp4-federated-joint-cohort-analysis#24]
- [x] Complete outstanding technical actions
  + [x] #14 Verify that memory requirements work
  + [x] #17 Verity that packages are installed in the Nextflow pod
- [x] Documentation
  + [x] #25 Rearrange the docs to separate general approach and workflow specific details
  + [x] #26 Write joint cohort genotyping documentation
  + [x] #27 Expand the docs to better establish context
- [x] Pipeline
  + [x] #29 Decide on the reference datasets
  + [x] #28 Find/write the demonstrator genotyping pipeline
  + [x] #30 Test and debug the pipeline
  + [x] #31 Find out about TESK deployment at EBI
- [x] Milestone
  + [x] #32 Fill in the milestone slide
  + [x] #33 Write the milestone report

**Comment by tskir** [comment]
* Decided to use two environments: CSC TESK + EBI LSF
* Decided to use two datasets: EGA synthetic dataset + GIAB
